config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get '/signup', to: "users#new"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum:6, maximum:100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    has_many :articles
    validates :username, presence: true,
                                uniqueness: { case_sensitive: false },
                                length: { minimum: 3, maximum: 25 }
    validates :email, presence: true, 
                                uniqueness: { case_sensitive: false },
                                length: { maximum: 105 },
                                format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    def show
        # byebug
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
        # redirect_to article_path(@article)
            redirect_to @article, notice: 'Article was successfully created.'
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        # byebug
        if @article.update(article_params)
            redirect_to @article, notice: "Article was updated successfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to articles_path, notice: "Welcome to alpha blog #{@user.username}."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:notice] = "Your account information updated successfully"
      redirect_to articles_path
     else
      render :edit
     end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="bg-gray-100 p-7">
<%= form_with(model: @article, local: true)  do |f| %>
    <p class="mb-4">
        <%= f.text_field :title, placeholder: "Title", class: "peer py-2.5 sm:py-3 px-4 ps-11 block w-full bg-white border-transparent rounded-lg sm:text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-700 dark:border-transparent dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600"  %>
    </p>
    <p>
        <%= f.text_area :description, rows: 10, placeholder: "Description", class: "peer py-2.5 sm:py-3 px-4 ps-11 block w-full bg-white border-transparent rounded-lg sm:text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-700 dark:border-transparent dark:text-neutral-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600" %>
    </p>
    <p class="mt-4">
     <%= f.submit class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-teal-100 text-teal-800 hover:bg-teal-200 focus:outline-hidden focus:bg-teal-200 disabled:opacity-50 disabled:pointer-events-none dark:text-teal-500 dark:bg-teal-800/30 dark:hover:bg-teal-800/20 dark:focus:bg-teal-800/20" %>
    </p>
<% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>
<%= link_to 'Cancel', articles_path %>

app/views/articles/index.html.erb
<h1>Articles list</h1>


    <% @articles.each do |article| %>



<div class="flex flex-col bg-white border border-gray-200 shadow-2xs rounded-xl dark:bg-neutral-900 dark:border-neutral-700 dark:shadow-neutral-700/70 mb-2 rounded-b-none">
  <div class="border-b border-gray-200 rounded-t-xl py-3 px-4 md:py-4 md:px-5 dark:border-neutral-700 text-center">
    <p class="mt-1 text-lg text-gray-500 dark:text-neutral-500 font-semibold italic">
      by <%= article.user.username if article.user %>
    </p>
  </div>
  <%# %>
  <div class="text-center">
    <h3 class="text-2xl font-bold text-gray-800 dark:text-white">
      <%= link_to article.title, article_path(article), class: "text-green-500" %>
    </h3>
    <p class="mt-2 text-gray-500 dark:text-neutral-400 text-lg">
      <%= truncate(article.description, length: 100) %>
    </p>
    
<div class="mt-2">
    <%= link_to 'Show', article_path(article), class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-teal-500 text-white hover:bg-teal-600 focus:outline-hidden focus:bg-teal-600 disabled:opacity-50 disabled:pointer-events-none" %>

    <%= link_to 'Edit', edit_article_path(article), class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 focus:outline-hidden focus:bg-blue-700 focus:outline-hidden focus:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none" %>

    <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:  "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-red-500 text-white hover:bg-red-600 focus:outline-hidden focus:bg-red-600 disabled:opacity-50 disabled:pointer-events-none" %>

</div>
 <div class="mt-2 bg-gray-100 border-b border-gray-200 text-sm text-gray-800 p-4 dark:bg-neutral-800 dark:border-neutral-700 dark:text-white">
    <span class="text-md text-gray-500 font-semibold">Created <%= article.created_at %> ago, </span> 
    <span class="text-md text-gray-500 font-semibold">Edited <%= article.updated_at %> ago</span>
  </div>
  </div>
</div>

    <% end %>
 
 <%= link_to 'Crete new ariticle', new_article_path %>

 

app/views/articles/new.html.erb
<div class="text-center pl-130 pr-130">
<h1 class="text-4xl dark:text-white">New article</h1>

<%= render 'form' %>
<%= link_to '[ Cancel and Return to ariticle listing ]', articles_path, class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent text-blue-600 hover:text-blue-800 focus:outline-hidden focus:text-blue-800 active:text-blue-800 disabled:opacity-50 disabled:pointer-events-none dark:text-blue-500 dark:hover:text-blue-400 dark:focus:text-blue-400 dark:active:text-blue-400" %>
</div>

app/views/articles/show.html.erb
<h1 class="text-xl text-center"><%= @article.title%></h1>
<div class="flex flex-col bg-white border border-gray-200 shadow-2xs dark:bg-neutral-900 dark:border-neutral-700 dark:shadow-neutral-700/70 mb-2 rounded-b-none">
  <div class="border-b border-gray-200 rounded-t-xl py-3 px-4 md:py-4 md:px-5 dark:border-neutral-700 text-center">
    <p class="mt-1 text-lg text-gray-500 dark:text-neutral-500 font-semibold">
      by <%= @article.user.username if @article.user %>
    </p>
  </div>
  <%# %>
<div class="p-5 text-xl">
    <p class="mt-2 text-gray-500 dark:text-neutral-400 ">
      <%= simple_format(@article.description) %>
    </p>
</div>
    
<div class="mt-2 text-center">
    <%= link_to 'Edit', edit_article_path(@article), class: "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 focus:outline-hidden focus:bg-blue-700 focus:outline-hidden focus:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none" %>

    <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:  "py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-transparent bg-red-500 text-white hover:bg-red-600 focus:outline-hidden focus:bg-red-600 disabled:opacity-50 disabled:pointer-events-none" %>

</div>
 <div class="mt-2 bg-gray-100 border-b border-gray-200 text-sm text-gray-800 p-4 dark:bg-neutral-800 dark:border-neutral-700 dark:text-white">
    <span class="text-md text-gray-500 font-semibold">Created <%= @article.created_at %> ago, </span> 
    <span class="text-md text-gray-500 font-semibold">Edited <%= @article.updated_at %> ago</span>
  </div>

    <%# <a class="mt-3 inline-flex items-center gap-x-1 text-sm font-semibold rounded-lg border border-transparent text-blue-600 decoration-2 hover:text-blue-700 hover:underline focus:underline focus:outline-hidden focus:text-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:text-blue-500 dark:hover:text-blue-600 dark:focus:text-blue-600" href="#">
      Card link
      <svg class="shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="m9 18 6-6-6-6"></path>
      </svg>
    </a> %>
  </div>
</div>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
  <div id="dismiss-alert" class="hs-removing:translate-x-5 hs-removing:opacity-0 transition duration-300 bg-teal-50 border border-teal-200 text-sm text-teal-800 rounded-lg p-4 dark:bg-teal-800/10 dark:border-teal-900 dark:text-teal-500" role="alert" tabindex="-1" aria-labelledby="hs-dismiss-button-label">
  <div class="flex">
    <div class="shrink-0">
      <svg class="shrink-0 size-4 mt-0.5" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"></path>
        <path d="m9 12 2 2 4-4"></path>
      </svg>
    </div>
    <div class="ms-2">
      <h3 id="hs-dismiss-button-label" class="text-sm font-medium">
        <%= msg %>
      </h3>
    </div>
    <div class="ps-3 ms-auto">
      <div class="-mx-1.5 -my-1.5">
        <button type="button" id="destroy-btn" class="inline-flex bg-teal-50 rounded-lg p-1.5 text-teal-500 hover:bg-teal-100 focus:outline-hidden focus:bg-teal-100 dark:bg-transparent dark:text-teal-600 dark:hover:bg-teal-800/50 dark:focus:bg-teal-800/50" data-hs-remove-element="#dismiss-alert">
          <span class="sr-only">Dismiss</span>
          <svg class="shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M18 6 6 18"></path>
            <path d="m6 6 12 12"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>
<script>
  const element  = document.getElementById('dismiss-alert');
  const destroyBtn = document.querySelector('#destroy-btn');

  destroyBtn.addEventListener('click', () => {
    element.remove();
  });
</script>
   
  <% end %>

app/views/layouts/_navigation.html.erb
<div class="space-y-4">
  <header class="flex flex-wrap sm:justify-start sm:flex-nowrap w-full bg-gray-800 text-sm py-4 dark:bg-white">
    <nav class="w-full mx-auto px-4 sm:flex sm:items-center sm:justify-between">
      <div class="flex items-center justify-between">
        <a class="flex-none text-xl font-semibold text-white focus:outline-hidden focus:opacity-80 dark:text-neutral-800" href="/">ALPHA BLOG</a>
        <div class="sm:hidden">
          <button type="button" class="hs-collapse-toggle relative size-9 flex justify-center items-center gap-2 rounded-lg border border-gray-700 font-medium bg-gray-800 text-gray-400 shadow-2xs align-middle hover:bg-gray-700/20 focus:outline-hidden focus:bg-gray-700/20 text-sm dark:bg-white dark:hover:bg-gray-100 dark:border-gray-200 dark:text-gray-600 dark:focus:bg-gray-100" id="hs-navbar-dark-collapse" aria-expanded="false" aria-controls="hs-navbar-dark" aria-label="Toggle navigation" data-hs-collapse="#hs-navbar-dark">
            <svg class="hs-collapse-open:hidden shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" x2="21" y1="6" y2="6"/><line x1="3" x2="21" y1="12" y2="12"/><line x1="3" x2="21" y1="18" y2="18"/></svg>
            <svg class="hs-collapse-open:block hidden shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
            <span class="sr-only">Toggle</span>
          </button>
        </div>
      </div>
      <div id="hs-navbar-dark" class="hidden hs-collapse overflow-hidden transition-all duration-300 basis-full grow sm:block" aria-labelledby="hs-navbar-dark-collapse">
        <div class="flex flex-col gap-4 mt-3 mb-3 sm:flex-row sm:items-center sm:justify-end sm:mt-0 sm:ps-5">
          <a class="font-medium text-white focus:outline-hidden dark:text-black" href="/articles" aria-current="page">Articles</a>
          <a class="font-medium text-gray-400 hover:text-gray-500 focus:outline-hidden focus:text-gray-500 dark:text-neutral-500 dark:hover:text-neutral-400 dark:focus:text-neutral-400" href="#">Account</a>
          <a class="font-medium text-gray-400 hover:text-gray-500 focus:outline-hidden focus:text-gray-500 dark:text-neutral-500 dark:hover:text-neutral-400 dark:focus:text-neutral-400" href="#">Work</a>
          <a class="font-medium text-gray-400 hover:text-gray-500 focus:outline-hidden focus:text-gray-500 dark:text-neutral-500 dark:hover:text-neutral-400 dark:focus:text-neutral-400" href="/signup">Signup</a>
        </div>
      </div>
    </nav>
  </header>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <div class="p-10 bg-gray-300 h-screen">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'About', about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class=" text-left mt-2 bg-red-100 border border-red-200 text-sm text-red-800 rounded-lg p-4 dark:bg-red-800/10 dark:border-red-900 dark:text-red-500" role="alert" tabindex="-1" aria-labelledby="hs-soft-color-danger-label">
  

    <h2 class="text-lg text-red-500">Errors</h2>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
    <li class="text-red-500"><%= msg %></li>
    <% end %>
    </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
 <%= render 'shared/errors', obj: user %>

  <div class="my-5">
    <%= form.label :username %>
    <%= form.text_field :username, placeholder: "Username", class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user.errors[:username].none?, "border-red-400 focus:outline-red-600": user.errors[:username].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.email_field :email, placeholder: "Email", class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user.errors[:username].none?, "border-red-400 focus:outline-red-600": user.errors[:username].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: "Choose password", class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user.errors[:username].none?, "border-red-400 focus:outline-red-600": user.errors[:username].any?}] %>
  </div>
  <div class="inline">
    <%= form.submit(user.new_record? ? "Sign up": "Update account", class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer") %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Username:</strong>
    <%= user.username %>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<% content_for :title, "Users" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to "New user", new_user_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @users.any? %>
      <% @users.each do |user| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render user %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", user, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_user_path(user), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", user, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No users found.</p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :title, "Signup for Alpha Blog" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Signup for Alpha Blog</h1>

  <%= render "form", user: @user %>

  <%= link_to "Back to users", users_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<% content_for :title, "Showing user" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing user</h1>

  <%= render @user %>

  <%= link_to "Edit this user", edit_user_path(@user), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this user", @user, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>